// Firebase Configuration
// Values are injected at deploy time via window.__env (see env.js, generated by CI).
// For local development, create an env.js file with your real values (see env.example.js).
const firebaseConfig = {
  apiKey: window.__env.FIREBASE_API_KEY,
  authDomain: window.__env.FIREBASE_AUTH_DOMAIN,
  databaseURL: window.__env.FIREBASE_DATABASE_URL,
  projectId: window.__env.FIREBASE_PROJECT_ID,
  storageBucket: window.__env.FIREBASE_STORAGE_BUCKET,
  messagingSenderId: window.__env.FIREBASE_MESSAGING_SENDER_ID,
  appId: window.__env.FIREBASE_APP_ID
};

// Initialize Firebase
firebase.initializeApp(firebaseConfig);
window.database = firebase.database();
window.firebaseReady = true;

console.log('Firebase initialized successfully');
